before_script:
  - whoami
  - sudo docker --version

stages:
  - build
  - deploy

build:
  stage: build
  script: 
    - echo "Building the test app"
    - cd src/STA663-notebook; pwd; ls -la
    - ./build-test

deploy_staging:
  stage: deploy
  script:
    - echo "Deploy to staging server"
	- cd /srv/persistent-data/docker-scripts; ./run-test-instance
  environment:
    name: staging
  only:
  - master

deploy_prod:
  stage: deploy
  script:
    - echo "Building the production app"
    - cd src/STA663-notebook; pwd; ls -la
    - ./build-production
    - echo "Deploy to production server"
    - cd /srv/persistent-data/docker-scripts; ./run-everything
  environment:
    name: production
  when: manual
  only:
  - master