#!/bin/bash
#
# get the server HOSTID
#
INPUT=/srv/persistent-data/docker-scripts/hostID
OLDIFS=$IFS
IFS=,
[ ! -f $INPUT ] && { echo "$INPUT file not found"; exit 99; }
while read hostID
do
  MYHOSTID=$hostID
  echo $hostID:
done < $INPUT
IFS=$OLDIFS

port=443
MYHOSTID=07
sudo docker run --name jupyter-hiv2020-$port \
        -d -p 127.0.0.1\:\:8888 \
        --memory 5000M \
        --init \
        -e PASSWORD=$STAGING_TEST_PASSWORD \
        -e DISABLE_XSRF=TRUE \
        -e VIRTUAL_HOST=ipyn-az-$MYHOSTID.oit.duke.edu\:$port \
        -e MAP_VIRTUAL_PORT=$port \
        -v /srv/persistent-data/homedirs/monitoring-user/work\:/home/jovyan/work \
        -v /srv/persistent-data/homedirs/shared_space_hiv2020\:/shared_space \
        -v /srv/persistent-data/homedirs/instructorspace-hiv2020\:/data/:ro \
        -e NB_UID=1000 \
        -t jupyter-hiv-test2020
